### ISSUE TITLE
how can ı give variable size images to lasagne network ?

### ISSUE THREAD

**Issue by erogol** [dnouri/nolearn#111]
I have a set of images in different sizes. I would like to sample fixed size patches per batch from these images. However as far as I see from the code, nolearn interface expects to have a fixed numpy array dataset. Is there any way to handle this in nolearn?

**Comment by BenjaminBossan** [comment]
I believe this is something that is not directly supported by the Lasagne framework. At the very last, when the images are passed through the BatchIterator to the layers, they should have equal size, since the weight parameters of the net have fixed size.
Right now, I don't quite understand what you want to achieve, but it sounds like your problem could be solved if you pre-process the image data so that the patches are extracted beforehand and normalized in size. As mentioned, the BatchIterator could do this job if you change the transform method.

**Comment by dnouri** [comment]
One way to do this is to do manual batch generation in a loop that contains `net.fit()`.  Here's an example to illustrate this:

```python
net = NeuralNet(
    #...,
    max_epochs=1,
    )

for X, y in generate_patches():
    try:
        net.fit(X, y)
    except StopTraining:
        break
```

Here I'm raising a custom `StopTraining` exception in my `EarlyStopping` code that then stops the training loop.

Alternatively, you can sample from patches inside your `BatchIterator` code.  The `X` that you feed into `net.fit()` could be whole images (or filenames?) and the batch iterator would then return the patches.

**Comment by fusionlove** [comment]
Are there performance issues with the net.fit loop?
