### ISSUE TITLE
Testing caffe/decaf during continuous integration?

### ISSUE THREAD

**Issue by arogozhnikov** [dnouri/nolearn#176]
Currently it seems there is no testing for caffe wrappers on travis-ci.

There is some problem with environment/hardware or installing takes too long?
Or you're going to drop support for those libraries?

**Comment by dnouri** [comment]
The lack of tests for the caffe wrapper is a bug.

Also I'm afraid the wrapper has also become quite outdated by now.  Caffe has also grown better Python support itself since `nolearn.caffe` was written, but I haven't exactly kept up with it.

If you're using the `nolearn.caffe` and finding an issue with it, please report.
